server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        ddl-auto: update

keycloak:
  realm: test-realm
  auth-server-url: http://localhost:8080
  resource: test-client-id
  bearer-only: true
  public-client: true
